name: deepAL
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip>=21.2.2
  - numpy>=1.21.2
  - scipy>=1.7.3
  - scikit-learn>=1.0.2
  - matplotlib>=3.5.1
  - pandas>=1.3.5
  - tqdm>=4.64.0
  - pyyaml>=6.0
  - pillow>=8.4.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - faiss-gpu>=1.7.2
  - openml=0.12.2
  - tensorboardx=2.2
  - cython-blis>=0.7.7
  - thinc>=7.4.5
  - requests
  - ipdb>=0.13.9
  - wilds>=2.0.0
  - wandb>=0.13.0
  - pip:
      - opencv-python>=4.5.5
      - toma>=1.1.0
      - spacy>=3.0
