name: deepAL2
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip=21.2.2
  - numpy=1.21.2
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - pandas=1.3.5
  - tqdm=4.64.0
  - pyyaml=6.0
  - pillow>=8.4.0
  - torchvision=0.11.3
  - pytorch=1.10.2
  - cudatoolkit=11.3
  - torchaudio=0.10.2
  - faiss-gpu=1.7.2
  - openml=0.12.2
  - tensorboardx=2.2
  - spacy=2.3.5
  - cython-blis=0.7.7
  - thinc=7.4.5
  - tqdm
  - requests
  - pip:
      - apex==0.1
